# Generated by Django 5.2.6 on 2025-11-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodrecord",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="moodrecord",
            name="mood",
            field=models.CharField(max_length=20),
        ),
    ]
